### ISSUE TITLE
Project Peer Review- Adelaida 

### ISSUE THREAD

**Issue by adelaidau** [fantappie/project#3]
Technical Issues: 
-In the form under the contact site, the answer for the rating is pre-answered and a 10/10. It should be blank and a dropdown for selection.
- The link for your LinkedIn profile is not working.

Suggestions on Content:
- Do not include the project proposal on your website. Go directly to the topics you want to address in it.
- The rating in the contact form has values of 11/20 and 20/10. I would change this to more measurable values and that are more appropriate for the content of the website.
- I would change the "talk" in the contact form to "write your message here" or something that makes the website sound a little more professional.
- I would put a picture of yourself or your hobbies on the "about me page"
- I would connect the page "places" to something in your website, maybe explain your passion for traveling on the "about me" page.

**Comment by fantappie** [comment]
Thank you so much for the comments! I will be sure to fix where needed and add the content suggestions.
