### ISSUE TITLE
Peer Review from Billy Caso

### ISSUE THREAD

**Issue by billycaso** [fantappie/project#4]
Technical:
- I think you could space out the elements of the form a little bit on the contact page
- The last photo on the places page is not showing up for me

Content:
- On the places page, I think it would be cool to add some brief info about your experiences in those countries
- Maybe move the contact and sitemap pages to the end of your header 

I think this is a very interesting website concept, kind of like a dynamic resume.

**Comment by fantappie** [comment]
Thank you very much for your comments! I will be sure to edit my site accordingly.
